config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :companies
  resources :billing_details
  resources :settings  
  resources :versions
  resources :service_details
  resources :least_cost_routes
  resources :suppliers
  #resources :supplier_rates, shallow: true do
  #	  resources :rates, :as => :supplier_rate_details
  #end                  
  resources :supplier_rates
  resources :rates                  
  #resources :customer_rates, shallow: true do
  #	  resources :rates, :as => :customer_rate_details
  #end  
  resources :customer_rates
  resources :rates            
  resources :rate_details
  resources :legacy_users
  resources :legacy_addresses
  resources :destinations
  resources :directions
  resources :call_detail_records
  resources :devices
  resources :locations
  resources :location_rules
  resources :country_rates
  
  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :bills, :only => [:index, :show]
  resources :currencies, :only => [:index]  
  
  resources :rate_details
  
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :confirmations => "confirmations" }

  resources :users  
  resources :users, :only => [:show, :index] do  
  	  member do
  	  	get 'invite'  
  	  	put 'reinvite'
  	  	put 'reset'
  	  end

  end
  
  unauthenticated do      
    devise_scope :user do
      root :to => "devise/sessions#new"
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
  end
  
  authenticated :user do
    devise_scope :user do
      root :to => "users#index", :as => :authenticated_root
      
      match '/supplier_rates/import' => 'supplier_rates#import', :via => [:put, :post], :as => :import_supplier_rates
      match '/customer_rates/import' => 'customer_rates#import', :via => [:put, :post], :as => :import_customer_rates

      post '/supplier_rates/:id/empty' => 'supplier_rates#empty', :as => :empty_supplier_rate
      post '/customer_rates/:id/empty' => 'customer_rates#empty', :as => :empty_customer_rate      
      
      match '/settings/update' => 'settings#update', :via => :put
      post '/settings/apply' => 'settings#apply', :as => :apply_settings
      post '/users/:id/become' => 'users#become', :as => :become_user
      post '/companies/:version_id/undo', to: 'companies#undo', as: :undo_company
      post '/addresses/:version_id/undo', to: 'addresses#undo', as: :undo_address
      post '/least_cost_routes/:version_id/undo', to: 'least_cost_routes#undo', as: :undo_least_cost_route
      post '/suppliers/:version_id/undo', to: 'suppliers#undo', as: :undo_supplier
      post '/locations/:version_id/undo', to: 'locations#undo', as: :undo_location    
      post '/supplier_rates/:version_id/undo', to: 'supplier_rates#undo', as: :undo_supplier_rate
      post '/legacy_users/:version_id/undo', to: 'legacy_users#undo', as: :undo_legacy_user
    end
  end 
        
  resources :errors, :only => [:show]
  
  
  %w( 404 422 500 ).each do |error_code|
    get error_code, :to => "errors#show", :code => error_code
  end
  match '*a', :to => 'errors#404', :via => :get   

  #match '/404', :to => 'errors#not_found', :via => :get
  #match '/422', :to => 'errors#server_error', :via => :get
  #match '/500', :to => 'errors#server_error', :via => :get 
  
  
end

app/views/services/_grid.html.haml
= grid(@services_grid, show_filters: :always, hide_submit_button: true) do |g|
                                                                               
  - g.blank_slate :partial => "empty_grid"
  
  //- g.action_column
                                                            

  - g.column name: 'name'.titleize, attribute: 'name' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'name', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.name              

  - g.column name: 'login_address'.titleize, attribute: 'login_address' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_address', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.login_address              

  - g.column name: 'login_name'.titleize, attribute: 'login_name' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_name', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.login_name              

  - g.column name: 'login_password'.titleize, attribute: 'login_password' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_password', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.login_password              

  - g.column name: 'api_key_1'.titleize, attribute: 'api_key_1' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'api_key_1', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.api_key_1              

  - g.column name: 'api_key_2'.titleize, attribute: 'api_key_2' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'api_key_2', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.api_key_2              

  - g.column name: 'service_type'.titleize, attribute: 'service_type' do |service|                                                                                                        
    - link_to service_path(service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'service_type', url: service_path(service), 'original-title' => 'update service details'.titleize} do      
      - service.service_type              

  
  - g.column class: 'col-xs' do |service|  
    - link_to "...", service_path(service), title: "Advanced", data: { container: "body", toggle: "tooltip", placement: "left"}, :class => ''
      
  

app/views/services/index.html.haml
= render 'nav_state'

%header.collections-header
 %nav.pull-right.actions
  = link_to 'New', new_service_path, :class => "btn btn-sm btn-primary ladda-button", :'data-style' => "expand-left"
  
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General      
   
.tab-content  
 #one.tab-pane.active= render 'grid'
 

app/views/services/new.html.haml
= render 'nav_state'
    
%header.collections-header
 %h6.pull-left Create Service
 %nav.pull-right.actions
  = link_to 'Back', services_path, :class => "btn btn-sm btn-primary ladda-button", :data => { :style => "expand-left" }
    
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General 
   
.tab-content   
 #one.full-width.tab-pane.active
         
  = form_for @service, :html => { class: "operator-form form form-horizontal" } do |f|
   %fieldset
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :name, :placeholder=> 'name'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :login_address, :placeholder=> 'login_address'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :login_name, :placeholder=> 'login_name'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :login_password, :placeholder=> 'login_password'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :api_key_1, :placeholder=> 'api_key_1'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :api_key_2, :placeholder=> 'api_key_2'.titleize, :class => "form-control"
    .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.number_field :service_type, :placeholder=> 'service_type'.titleize, :class => "form-control"
    .form-group
     .col-lg-12        
      = f.submit 'create'.titleize, :class => "btn btn-info pull-right", :remote => false

app/views/services/show.html.haml
= render 'nav_state'

%header.collections-header
 %h5.pull-left= @service.name.titleize
 %nav.pull-right.actions
  .btn-group                    
   
   = link_to "create_service_detail".titleize, new_service_detail_path, :class => "btn btn-sm btn-info"
   = link_to 'Back', services_path, :class => "btn btn-sm btn-primary ladda-button", :data => { :style => "expand-left" }

%nav.tabs.nav-tabs
 %ul
  %li.active
   %a(data-toggle="tab" href="#one") General
   
.tab-content  
 #one.tab-pane.active
  .tab-spacer 
  
  
   %p
    %strong Name:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'name', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.name
   %p
    %strong Login Address:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_address', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.login_address
   %p
    %strong Login Name:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_name', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.login_name
   %p
    %strong Login Password:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'login_password', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.login_password
   %p
    %strong Api Key 1:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'api_key_1', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.api_key_1
   %p
    %strong Api Key 2:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'api_key_2', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.api_key_2
   %p
    %strong Service Type:                                   
    = link_to service_path(@service), class: 'editable', data: { container: 'body', type: 'text', model: 'service', name: 'service_type', url: service_path(@service), 'original-title' => 'update carrier details'.titleize} do
     = @service.service_type
                                                          

  .btn-group.pull-right 
   = link_to service_path(@service), :method => :delete, :data => {remote: "false", container: "body", toggle: "tooltip", placement: "top"}, :class => 'btn btn-danger' do
    %i.fui-2-trash