config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :companies
  resources :billing_details
  resources :settings  
  resources :versions
  resources :service_details
  resources :least_cost_routes
  resources :suppliers
  #resources :supplier_rates, shallow: true do
  #	  resources :rates, :as => :supplier_rate_details
  #end                  
  resources :supplier_rates
  resources :rates                  
  #resources :customer_rates, shallow: true do
  #	  resources :rates, :as => :customer_rate_details
  #end  
  resources :customer_rates
  resources :rates            
  resources :rate_details
  resources :legacy_users
  resources :legacy_addresses
  resources :destinations
  resources :directions
  resources :call_detail_records
  resources :devices
  resources :locations
  resources :location_rules
  resources :country_rates
  
  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :bills, :only => [:index, :show]
  resources :currencies, :only => [:index]  
  
  resources :rate_details
  
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :confirmations => "confirmations" }

  resources :users  
  resources :users, :only => [:show, :index] do  
  	  member do
  	  	get 'invite'  
  	  	put 'reinvite'
  	  	put 'reset'
  	  end

  end
  
  unauthenticated do      
    devise_scope :user do
      root :to => "devise/sessions#new"
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
  end
  
  authenticated :user do
    devise_scope :user do
      root :to => "users#index", :as => :authenticated_root
      
      match '/supplier_rates/import' => 'supplier_rates#import', :via => [:put, :post], :as => :import_supplier_rates
      match '/customer_rates/import' => 'customer_rates#import', :via => [:put, :post], :as => :import_customer_rates

      post '/supplier_rates/:id/empty' => 'supplier_rates#empty', :as => :empty_supplier_rate
      post '/customer_rates/:id/empty' => 'customer_rates#empty', :as => :empty_customer_rate      
      
      match '/settings/update' => 'settings#update', :via => :put
      post '/settings/apply' => 'settings#apply', :as => :apply_settings
      post '/users/:id/become' => 'users#become', :as => :become_user
      post '/companies/:version_id/undo', to: 'companies#undo', as: :undo_company
      post '/addresses/:version_id/undo', to: 'addresses#undo', as: :undo_address
      post '/least_cost_routes/:version_id/undo', to: 'least_cost_routes#undo', as: :undo_least_cost_route
      post '/suppliers/:version_id/undo', to: 'suppliers#undo', as: :undo_supplier
      post '/locations/:version_id/undo', to: 'locations#undo', as: :undo_location    
      post '/supplier_rates/:version_id/undo', to: 'supplier_rates#undo', as: :undo_supplier_rate
      post '/legacy_users/:version_id/undo', to: 'legacy_users#undo', as: :undo_legacy_user
    end
  end 
        
  resources :errors, :only => [:show]
  
  
  %w( 404 422 500 ).each do |error_code|
    get error_code, :to => "errors#show", :code => error_code
  end
  match '*a', :to => 'errors#404', :via => :get   

  #match '/404', :to => 'errors#not_found', :via => :get
  #match '/422', :to => 'errors#server_error', :via => :get
  #match '/500', :to => 'errors#server_error', :via => :get 
  
  
end

app/models/call_detail_record.rb
class CallDetailRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection "mysql2"
  self.table_name = 'calls'
  
  has_paper_trail
  
  
  #scope :on, -> { where(calldate > '2014-05-01') }
	  
end





app/controllers/call_detail_records_controller.rb
class CallDetailRecordsController < ApplicationController
  before_action :set_call_detail_record, only: [:show, :edit, :update, :destroy]
  before_action :load_grid, only: [:index]
  before_action :set_controller_section
  before_filter :authenticate_user!  
  load_and_authorize_resource
  # respond_to :html, :json, :js  
  
  def controller_section
   #self.class.name.split("::").first
   "reports"   
  end	
           
  def set_controller_section
   @current_section = self.controller_section.titleize
  end	  
        
  # GET /call_detail_records
  def index
    # @call_detail_records = CallDetailRecord.all
    @call_detail_record_versions = Version.where(:item_type => 'CallDetailRecord')
  end

  # GET /call_detail_records/1
  def show
  	  
  end

  # GET /call_detail_records/new
  def new
    @call_detail_record = CallDetailRecord.new
  end

  # GET /call_detail_records/1/edit
  #def edit
  #end

  # POST /call_detail_records
  def create
    @call_detail_record = CallDetailRecord.new(call_detail_record_params)
    respond_to do |format|
      if @call_detail_record.save
        #format.html { redirect_to @call_detail_record, notice: 'CallDetailRecord was successfully created. #{make_redo_link}' }
        format.html { redirect_to @call_detail_record, notice: 'CallDetailRecord was successfully created.' }
        format.js   {}
        format.json { render json: @call_detail_record, status: :created, location: @call_detail_record }
      else
        format.html { render action: "new" }
        format.json { render json: @call_detail_record.errors, status: :unprocessable_entity }
      end
    end
  
  end
                          
  # PATCH/PUT /call_detail_records/1
  def update
    @call_detail_record.update(call_detail_record_params)     
    flash[:notice] = "CallDetailRecord was successfully updated. #{make_undo_link}" if @call_detail_record.save
    #respond_with @call_detail_record          
    render :json => @call_detail_record
  end                                                 

  # DELETE /call_detail_records/1
  def destroy   
    
    respond_to do |format|
      if @call_detail_record.destroy
        flash[:notice] = 'CallDetailRecord was successfully destroyed.'
        format.js
        format.html
      else
        format.html { render action: "index" }
      end
    end    
    
  end           
  
  def undo
    @call_detail_record_version = PaperTrail::Version.find_by_id(params[:call_detail_record_id])
   
    begin
      if @call_detail_record_version.reify
        @call_detail_record_version.reify.save
      else
        @call_detail_record_version.item.destroy
      end
      flash[:notice] = "Update undone. #{make_redo_link}"
    rescue
      flash[:alert] = "Failed undoing the action."
    ensure
      redirect_to call_detail_records_path
    end                                                          
  end  
  

  protected
  
    def make_undo_link 
      view_context.link_to 'Undo the last update', undo_call_detail_record_path(@call_detail_record.versions.last), method: :post, class: 'alert-link'
    end
                                                
    def make_redo_link
      params[:redo] == "true" ? link = "Undo the last update" : link = "Redo the last update"
      view_context.link_to link, undo_call_detail_record_path(@call_detail_record_version.next, redo: !params[:redo]), method: :post, class: 'alert-link'
    end    
    
  private
                       
    def load_grid 
      @call_detail_records_grid = initialize_grid(CallDetailRecord, 
      	  per_page: 1000,
      	  name: 'call_detail_records',
      	  conditions: ["calldate > ?", Time.now - 2.months],
          order: 'calldate',
          order_direction: 'desc',      	  
          enable_export_to_csv: true,        
          csv_file_name: 'call_detail_records'  	  	  
      )
      export_grid_if_requested
    end        
    
 
        
    # Use callbacks to share common setup or constraints between actions.
    def set_call_detail_record
      @call_detail_record = CallDetailRecord.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def call_detail_record_params
      params.require(:call_detail_record).permit(:name, :server_ip, :tariff_id)
    end
end

app/views/call_detail_records/_grid.html.haml
= grid(@call_detail_records_grid, show_filters: :always, hide_submit_button: true) do |g|
                                                                               
  - g.blank_slate :partial => "empty_grid"
  
  - g.column name: 'calldate'.titleize, attribute: 'calldate', filter: false do |call_detail_record|                                                                                                        
    - call_detail_record.calldate              
  
  - g.column name: 'src'.titleize, attribute: 'src' do |call_detail_record|
    - call_detail_record.src   
    
  - g.column name: 'dst'.titleize, attribute: 'dst' do |call_detail_record|
    - call_detail_record.dst 
   
  - g.column name: 'duration'.titleize, attribute: 'duration', filter: false do |call_detail_record|
    - call_detail_record.duration 

  - g.column name: 'billsec'.titleize, attribute: 'billsec', filter: false do |call_detail_record|
    - call_detail_record.billsec 

  - g.column name: 'disposition'.titleize, attribute: 'disposition', custom_filter: :auto do |call_detail_record|
    - call_detail_record.disposition     

  - g.column name: 'provider_price'.titleize, attribute: 'provider_price', filter: false do |call_detail_record|
    - call_detail_record.provider_price 

  - g.column name: 'user_price'.titleize, attribute: 'user_price', filter: false do |call_detail_record|
    - call_detail_record.user_price 
    

  - g.column name: 'hangupcause'.titleize, attribute: 'hangupcause' do |call_detail_record|
    - call_detail_record.hangupcause     
  
  - g.column name: 'originator_ip'.titleize, attribute: 'originator_ip' do |call_detail_record|
    - call_detail_record.originator_ip 

  - g.column name: 'terminator_ip'.titleize, attribute: 'terminator_ip' do |call_detail_record|
    - call_detail_record.terminator_ip 
  
  - g.column class: 'col-md-1' do |call_detail_record|  
    - link_to call_detail_record_path(call_detail_record) do
      %i.fui-2-eye     

app/views/call_detail_records/index.html.haml
= render 'nav_state'

%header.collections-header
 %nav.pull-right.actions
  = link_to call_detail_records_path, :class => "btn btn-sm btn-default" do
   %i.fui-2-download  
   
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General      
   
.tab-content  
 #one.tab-pane.active= render 'grid'
 

app/views/call_detail_records/show.html.haml
= render 'nav_state'

- content_for :javascript do
 :javascript
  $('input[type="file"]').fileinput('refresh')

%header.collections-header
 %nav.pull-right.actions
  = link_to 'Back', least_cost_routes_path, :class => "btn btn-sm btn-primary ladda-button", :data => { :style => "expand-left" }
  
  
%nav.tabs.nav.nav-tabs 
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General 
   
.tab-content  
 #one.tab-pane.active  
 
  %div(style='padding:15px')
   %h5= link_to @least_cost_route.name, '#', class: 'editable', data: { name: 'name', container: "body", placement: "right", type: 'text', model: 'least_cost_route', url: least_cost_route_path(@least_cost_route), 'original-title' => 'Update Address'}
   %br
   %p     
    %strong Order:    
    = link_to @least_cost_route.order, '#', class: 'editable', data: { name: 'order', container: "body", mode: 'inline', placement: "right", type: 'text', model: 'least_cost_route', url: least_cost_route_path(@least_cost_route), 'original-title' => 'Update Address'}
    %br   
    %strong Failover:  
    - if @least_cost_route.no_failover
     = "N/A"
    - else
     = link_to Supplier.find(@least_cost_route.failover_provider_id).name, supplier_path(Supplier.find(@least_cost_route.failover_provider_id)) 
    
   //- @providers = LeastCostRouteDetail.where(:lcr_id => @least_cost_route.id)
   - @suppliers = @least_cost_route.suppliers
   %table.table.table-bordered.table-striped.sortable.pull-left
    %thead
     %tr       
      %th Name 
      %th IP Address
      %th Balance
    %tbody            
                            
     - @suppliers.each do |p|
      %tr
       %td= p.name                 
       %td= p.server_ip 
       %td= p.balance
          
 
  
   
  .col-lg-12  
   .btn-group.pull-right        
    = link_to least_cost_route_path(@least_cost_route), method: :delete, title: "Delete Least Cost Route", data: { remote: "true", container: "body", toggle: "tooltip", placement: "left"}, :class => 'btn btn-danger' do
     %i.fui-2-trash     
    
      