config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :companies
  resources :billing_details
  resources :settings  
  resources :versions
  resources :service_details
  resources :least_cost_routes
  resources :suppliers
  #resources :supplier_rates, shallow: true do
  #	  resources :rates, :as => :supplier_rate_details
  #end                  
  resources :supplier_rates
  resources :rates                  
  #resources :customer_rates, shallow: true do
  #	  resources :rates, :as => :customer_rate_details
  #end  
  resources :customer_rates
  resources :rates            
  resources :rate_details
  resources :legacy_users
  resources :legacy_addresses
  resources :destinations
  resources :directions
  resources :call_detail_records
  resources :devices
  resources :locations
  resources :location_rules
  resources :country_rates
  
  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :bills, :only => [:index, :show]
  resources :currencies, :only => [:index]  
  
  resources :rate_details
  
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :confirmations => "confirmations" }

  resources :users  
  resources :users, :only => [:show, :index] do  
  	  member do
  	  	get 'invite'  
  	  	put 'reinvite'
  	  	put 'reset'
  	  end

  end
  
  unauthenticated do      
    devise_scope :user do
      root :to => "devise/sessions#new"
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
  end
  
  authenticated :user do
    devise_scope :user do
      root :to => "users#index", :as => :authenticated_root
      
      match '/supplier_rates/import' => 'supplier_rates#import', :via => [:put, :post], :as => :import_supplier_rates
      match '/customer_rates/import' => 'customer_rates#import', :via => [:put, :post], :as => :import_customer_rates

      post '/supplier_rates/:id/empty' => 'supplier_rates#empty', :as => :empty_supplier_rate
      post '/customer_rates/:id/empty' => 'customer_rates#empty', :as => :empty_customer_rate      
      
      match '/settings/update' => 'settings#update', :via => :put
      post '/settings/apply' => 'settings#apply', :as => :apply_settings
      post '/users/:id/become' => 'users#become', :as => :become_user
      post '/companies/:version_id/undo', to: 'companies#undo', as: :undo_company
      post '/addresses/:version_id/undo', to: 'addresses#undo', as: :undo_address
      post '/least_cost_routes/:version_id/undo', to: 'least_cost_routes#undo', as: :undo_least_cost_route
      post '/suppliers/:version_id/undo', to: 'suppliers#undo', as: :undo_supplier
      post '/locations/:version_id/undo', to: 'locations#undo', as: :undo_location    
      post '/supplier_rates/:version_id/undo', to: 'supplier_rates#undo', as: :undo_supplier_rate
      post '/legacy_users/:version_id/undo', to: 'legacy_users#undo', as: :undo_legacy_user
    end
  end 
        
  resources :errors, :only => [:show]
  
  
  %w( 404 422 500 ).each do |error_code|
    get error_code, :to => "errors#show", :code => error_code
  end
  match '*a', :to => 'errors#404', :via => :get   

  #match '/404', :to => 'errors#not_found', :via => :get
  #match '/422', :to => 'errors#server_error', :via => :get
  #match '/500', :to => 'errors#server_error', :via => :get 
  
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  before_filter :authenticate_user!	
  before_action :set_controller_section 
  before_action :set_setting_file
  
  def controller_section
   "operator"                      
  end	
  
  def index
  end

  def apply
    head :ok
  end
  

  
  def create
  	  
    if (params[:key] && params[:value])
        	  
      @new_setting = "#{params[:key]}: #{params[:value]}"
      if File.open(@setting_file, 'a+') { |f| f.write(@new_setting) }
        flash[:notice] = "Setting was successfully created."
        redirect_to :action => :index
      else
        flash[:notice] = "There was a problem creating the Setting"
        render :new
      end
    end
  	  
  end
  
  def update
  	  
    params[:settings].each do |key, value|  
      @settings[key] = value
    end
    
    if File.open(@setting_file, 'w') { |f| YAML.dump(@settings, f) }            	  	
      flash[:notice] = "Setting was successfully updated."
      render :json => @settings
    else
      flash[:notice] = "There was a problem updating the Setting"
      render :json => :unprocessable_entity
    end    

  end   
  
  def apply
    #Figaro.application = Figaro::Application.new(environment: "development", path: "/srv/voxbox-service-nodes/config/application.yml")
    #Figaro.load
    #flash[:notice] = "Settings were successfully applied." if Figaro::Rails::Application.new.load
  end

  private
    
  def set_controller_section
   @current_section = self.controller_section.titleize
  end    
  
  def set_setting_file
    @setting_file = "#{Rails.root}/config/application.yml"
    @settings = YAML.load_file(@setting_file)
  end
    
end

app/views/settings/index.html.haml
= render 'nav_state'

%header.collections-header
 %nav.pull-right.actions
  = link_to settings_path, :class => "btn btn-sm btn-default" do
   %i.fui-2-download
    
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General  
   
.tab-content  
 #one.tab-pane.active

  %table.table-heading.table-striped.table-bordered.table
   %thead
    %tr
     %th Key
     %th Value
     
   %tbody
    - @settings.each_pair do |k,v|
     %tr
      %td= k
      %td= link_to v, '#', class: 'editable', data: { mode: 'inline', name: k, container: "body", placement: "bottom", type: 'text', model: 'settings', url: settings_update_path, 'original-title' => 'Update Setting'}

app/views/settings/new.html.haml
= render 'nav_state'

%header.collections-header
 %h6.pull-left Create Setting
 %nav.pull-right.actions
  = link_to 'Back', settings_path, :class => "btn btn-sm btn-primary ladda-button", :'data-style' => "expand-left"
    
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General 
   
.tab-content   
 #one.tab-pane.active
 
  = form_tag({:action => 'create', :controller => 'settings'}, {:class => "operator-form form form-horizontal"}) do
   %fieldset
    %legend 
    
    .form-group.inputs
     .col-lg-12       
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = text_field_tag 'key', nil, class: "form-control", :placeholder=> "key".titleize, :autofocus => true  
  
    .form-group.inputs
     .col-lg-12       
      .input-group
       %span.input-group-addon
        %i.fui-2-mail
       = text_field_tag 'value', nil, :class => "form-control", :placeholder=> "value".titleize
    
       
    .form-group
     .col-lg-12        
      = submit_tag 'create'.titleize, :class => "btn btn-info pull-right"
   

         
            