config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :companies
  resources :billing_details
  resources :settings  
  resources :versions
  resources :service_details
  resources :least_cost_routes
  resources :suppliers
  #resources :supplier_rates, shallow: true do
  #	  resources :rates, :as => :supplier_rate_details
  #end                  
  resources :supplier_rates
  resources :rates                  
  #resources :customer_rates, shallow: true do
  #	  resources :rates, :as => :customer_rate_details
  #end  
  resources :customer_rates
  resources :rates            
  resources :rate_details
  resources :legacy_users
  resources :legacy_addresses
  resources :destinations
  resources :directions
  resources :call_detail_records
  resources :devices
  resources :locations
  resources :location_rules
  resources :country_rates
  
  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :bills, :only => [:index, :show]
  resources :currencies, :only => [:index]  
  
  resources :rate_details
  
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :confirmations => "confirmations" }

  resources :users  
  resources :users, :only => [:show, :index] do  
  	  member do
  	  	get 'invite'  
  	  	put 'reinvite'
  	  	put 'reset'
  	  end

  end
  
  unauthenticated do      
    devise_scope :user do
      root :to => "devise/sessions#new"
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
  end
  
  authenticated :user do
    devise_scope :user do
      root :to => "users#index", :as => :authenticated_root
      
      match '/supplier_rates/import' => 'supplier_rates#import', :via => [:put, :post], :as => :import_supplier_rates
      match '/customer_rates/import' => 'customer_rates#import', :via => [:put, :post], :as => :import_customer_rates

      post '/supplier_rates/:id/empty' => 'supplier_rates#empty', :as => :empty_supplier_rate
      post '/customer_rates/:id/empty' => 'customer_rates#empty', :as => :empty_customer_rate      
      
      match '/settings/update' => 'settings#update', :via => :put
      post '/settings/apply' => 'settings#apply', :as => :apply_settings
      post '/users/:id/become' => 'users#become', :as => :become_user
      post '/companies/:version_id/undo', to: 'companies#undo', as: :undo_company
      post '/addresses/:version_id/undo', to: 'addresses#undo', as: :undo_address
      post '/least_cost_routes/:version_id/undo', to: 'least_cost_routes#undo', as: :undo_least_cost_route
      post '/suppliers/:version_id/undo', to: 'suppliers#undo', as: :undo_supplier
      post '/locations/:version_id/undo', to: 'locations#undo', as: :undo_location    
      post '/supplier_rates/:version_id/undo', to: 'supplier_rates#undo', as: :undo_supplier_rate
      post '/legacy_users/:version_id/undo', to: 'legacy_users#undo', as: :undo_legacy_user
    end
  end 
        
  resources :errors, :only => [:show]
  
  
  %w( 404 422 500 ).each do |error_code|
    get error_code, :to => "errors#show", :code => error_code
  end
  match '*a', :to => 'errors#404', :via => :get   

  #match '/404', :to => 'errors#not_found', :via => :get
  #match '/422', :to => 'errors#server_error', :via => :get
  #match '/500', :to => 'errors#server_error', :via => :get 
  
  
end

app/views/service_details/_grid.html.haml
= grid(@service_details_grid, show_filters: :always, hide_submit_button: true) do |g|
                                                                               
  - g.blank_slate :partial => "empty_grid"
  
  //- g.action_column
                                                            

  - g.column name: 'name', attribute: 'name' do |service_detail|                                                                                                        
    - link_to service_detail_path(service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: 'name', url: service_detail_path(service_detail), 'original-title' => 'update service details'.titleize} do      
      - service_detail.name              

  - g.column name: 'expires At', attribute: 'expires_at' do |service_detail|                                                                                                        
    - link_to service_detail_path(service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: 'expires_at', url: service_detail_path(service_detail), 'original-title' => 'update service details'.titleize} do      
      - service_detail.expires_at              

  - g.column name: 'description', attribute: 'description' do |service_detail|                                                                                                        
    - link_to service_detail_path(service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: 'description', url: service_detail_path(service_detail), 'original-title' => 'update service details'.titleize} do      
      - service_detail.description              

  - g.column name: 'additional Info', attribute: 'additional_info' do |service_detail|                                                                                                        
    - link_to service_detail_path(service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: 'additional_info', url: service_detail_path(service_detail), 'original-title' => 'update service details'.titleize} do      
      - service_detail.additional_info              

  - g.column name: 'service Id', attribute: 'service_id' do |service_detail|                                                                                                        
    - link_to service_detail_path(service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: 'service_id', url: service_detail_path(service_detail), 'original-title' => 'update service details'.titleize} do      
      - service_detail.service_id              

  
  - g.column class: 'col-xs' do |service_detail|  
    - link_to "...", service_detail_path(service_detail), title: "Advanced", data: { container: "body", toggle: "tooltip", placement: "left"}, :class => ''
      
  

app/views/service_details/index.html.haml
= render 'nav_state'

%header.collections-header
 %nav.pull-right.actions
  = link_to 'New', new_service_detail_path, :class => "btn btn-sm btn-primary ladda-button", :'data-style' => "expand-left"
  
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General  
  %li
   %a(href="#two" data-toggle="tab") Versions      
   
.tab-content  
 #one.full-width.tab-pane.active= render 'grid'
 
 #two.full-width.tab-pane

  %table.table-heading
   %thead
    %tr
     %th Timestamp
     %th User
     %th Changeset
     
   %tbody
   
    - @service_detail_versions.each do |version|
     %tr
      %td= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z")
      %td 
       - if (version.whodunnit && version.whodunnit != 'Guest')
        - begin
         = User.find(version.whodunnit).email
        - rescue
         = "Console"
      %td                  
       %pre= version.object_changes

app/views/service_details/new.html.haml
= render 'nav_state'
    
%header.collections-header
 %h6.pull-left Create Service Detail
 %nav.pull-right.actions
  = link_to 'Back', service_details_path, :class => "btn btn-sm btn-primary ladda-button", :data => { :style => "expand-left" }
    
%nav.tabs.nav.nav-tabs    
 %ul
  %li.active
   %a(href="#one" data-toggle="tab") General 
   
.tab-content   
 #one.full-width.tab-pane.active
         
  = form_for @service_detail, :html => { class: "operator-form form form-horizontal" } do |f|
   %fieldset
       .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_field :name, :placeholder=> Name, :class => "form-control"
       .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.date_select :expires_at, :placeholder=> Expires At, :class => "form-control"
       .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_area :description, :placeholder=> Description, :class => "form-control"
       .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.text_area :additional_info, :placeholder=> Additional Info, :class => "form-control"
       .form-group.inputs
     .col-lg-12
      .input-group
       %span.input-group-addon
        %i.fui-2-user
       = f.number_field :service_id, :placeholder=> Service, :class => "form-control"
       .form-group
     .col-lg-12        
      = f.submit 'create'.titleize, :class => "btn btn-info pull-right", :remote => false

app/views/service_details/show.html.haml
= render 'nav_state'

%header.collections-header
 %h5.pull-left= @service_detail.name.titleize
 %nav.pull-right.actions
  .btn-group                    
   
   = link_to "new service_details".titleize, new_service_detail_path, :class => "btn btn-sm btn-info"
   = link_to 'Back', service_details_path, :class => "btn btn-sm btn-primary ladda-button", :data => { :style => "expand-left" }

%nav.tabs.nav-tabs
 %ul
  %li.active
   %a(data-toggle="tab" href="#one") General
   
.tab-content  
 #one.tab-pane.active
  .tab-spacer 
  
  
     %p
    %strong Name:                                   
    = link_to service_detail_path(@service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: ''name', url: service_detail_path(@service_detail), 'original-title' => 'update carrier details'.titleize} do
     = @service_detail.name
     %p
    %strong Expires At:                                   
    = link_to service_detail_path(@service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: ''expires_at', url: service_detail_path(@service_detail), 'original-title' => 'update carrier details'.titleize} do
     = @service_detail.expires_at
     %p
    %strong Description:                                   
    = link_to service_detail_path(@service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: ''description', url: service_detail_path(@service_detail), 'original-title' => 'update carrier details'.titleize} do
     = @service_detail.description
     %p
    %strong Additional Info:                                   
    = link_to service_detail_path(@service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: ''additional_info', url: service_detail_path(@service_detail), 'original-title' => 'update carrier details'.titleize} do
     = @service_detail.additional_info
     %p
    %strong Service:                                   
    = link_to service_detail_path(@service_detail), class: 'editable', data: { container: 'body', type: 'text', model: 'service_detail', name: ''service_id', url: service_detail_path(@service_detail), 'original-title' => 'update carrier details'.titleize} do
     = @service_detail.service_id
                                                          

  .btn-group.pull-right 
   = link_to service_detail, :method => :delete, :data => {remote: "true", container: "body", toggle: "tooltip", placement: "top", confirm: 'Are you sure?' }, :class => 'btn btn-warning' do
    %i.fui-2-trash